### ISSUE TITLE
definir qual o endereço de domínio será utilizado

### ISSUE THREAD

**Issue by luzfcb** [PyNorte/pyconamazonia2017-site#1]
apos a decidir qual o endereço de domínio, deverão ser atualizados os seguintes arquivos.

https://github.com/PyNorte/pyconamazonia2017-site/blob/master/content/extra/CNAME
https://github.com/PyNorte/pyconamazonia2017-site/blob/master/CNAME
https://github.com/PyNorte/pyconamazonia2017-site/blob/master/Makefile#L10

**Comment by luzfcb** [comment]
Há 2 arquivos CNAME. Eu não sei quais dos dois é o correto... suponho que seja o que está na pasta content/extra

**Comment by lskbr** [comment]
Alterados para: amazonia.python.org.br
